Algoritmo "semnome"
// Disciplina  : Linguagem e Lógica de Programação
// Professor   : Alessandro Palmeira
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2019
Var
   // Seção de Declarações das variáveis
   n1: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   n1 <- -1

   Repita

      n1 <- n1+2
      escreva(n1)


   ate n1=249


Fimalgoritmo